In [1]:
import torch
import numpy as np
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import TensorDataset, DataLoader

# 讀取數據
train_normal = np.load('Data/train_normal.npy')
train_outer_break = np.load('Data/train_outer_break.npy')
train_inner_break = np.load('Data/train_inner_break.npy')

# 創建標籤
labels_normal = np.zeros(len(train_normal))
labels_outer_break = np.ones(len(train_outer_break))
labels_inner_break = np.full(len(train_inner_break), 2)

# 合併數據和標籤
X_train = np.concatenate((train_normal, train_outer_break, train_inner_break), axis=0)
y_train = np.concatenate((labels_normal, labels_outer_break, labels_inner_break), axis=0)
print(X_train.shape)
print(y_train.shape)

X_train_tensor = torch.tensor(X_train, dtype=torch.float).unsqueeze(1)  # Adding channel dimension
y_train_tensor = torch.tensor(y_train, dtype=torch.long)  # Assuming classification task

train_dataset = TensorDataset(X_train_tensor, y_train_tensor)
batch_size = 1  # Adjust the batch size according to your needs and hardware capabilities

# train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True)



(750, 10240)
(750,)


In [2]:
class VibrationCNN(nn.Module):
    def __init__(self):
        super(VibrationCNN, self).__init__()
        # Assuming 1D Convolutional layers for sequence data
        self.conv1 = nn.Conv1d(in_channels=1, out_channels=4, kernel_size=5, stride=1, padding=2)
        self.conv2 = nn.Conv1d(in_channels=4, out_channels=1, kernel_size=5, stride=1, padding=2)
        self.pool = nn.MaxPool1d(kernel_size=2, stride=2)
        # The size here might need adjustment based on the size after convolutions and pooling
        # Calculating the size: As input is 10240, after 3 pooling layers, the size is 10240/(2^3) = 1280
        self.fc1 = nn.Linear(1 * 1280, 20)
        self.fc2 = nn.Linear(20, 3)

    def forward(self, x):
        # x shape is [batch_size, channels, sequence_length]
        x = F.relu(self.conv1(x))
        x = self.pool(x)
        
        x = F.relu(self.conv2(x))
        x = self.pool(x)

        # Adjust the number of pool operations according to your model architecture
        # An additional pool operation as an example
        x = self.pool(x)
        
        # Flatten for the fully connected layer
        x = x.view(-1, 1 * 1280)  # Adjust the flattening size accordingly
        
        x = F.relu(self.fc1(x))
        x = self.fc2(x)  # No activation, as nn.CrossEntropyLoss() includes softmax
        
        return x


In [3]:
import torch.optim as optim
import base_func 
model_list = {
    "VibrationCNN" : lambda: VibrationCNN(),
}
model_name = "VibrationCNN"
loaders = base_func.get_dataloaders(train_dataset, 0.6, 0.5, 1)
phases = ['train','val']
base_func.train(model_list, "VibrationCNN", loaders, phases)

--------- INDEX checking ---------
Original: [0, 1, 2, 3, 4]
Shuffled: [601, 71, 426, 250, 724]
--------- INDEX shuffled ---------

Total number of samples: 750 datapoints
Number of train samples: 450 batches/ 450 datapoints
Number of val samples: 150 batches/ 150 datapoints
Number of test samples: 150 batches/ 150 datapoints

Training model: VibrationCNN
Total parameters: 25,728


Learning rate=0.001


  0%|          | 0/450 [00:00<?, ?it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')


 16%|█▌        | 70/450 [00:00<00:01, 264.10it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

 47%|████▋     | 211/450 [00:00<00:00, 486.49it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 78%|███████▊  | 350/450 [00:00<00:00, 565.62it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

100%|██████████| 450/450 [00:00<00:00, 464.07it/s]


torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

  0%|          | 0/150 [00:00<?, ?it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

100%|██████████| 150/150 [00:00<00:00, 1667.22it/s]


torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

  0%|          | 0/450 [00:00<?, ?it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 10%|█         | 46/450 [00:00<00:00, 418.32it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

 24%|██▍       | 109/450 [00:00<00:00, 509.26it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 36%|███▌      | 160/450 [00:00<00:00, 488.50it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

 51%|█████     | 228/450 [00:00<00:00, 539.78it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size

 64%|██████▍   | 288/450 [00:00<00:00, 541.89it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

 78%|███████▊  | 352/450 [00:00<00:00, 555.53it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 91%|█████████ | 408/450 [00:00<00:00, 540.40it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size

100%|██████████| 450/450 [00:00<00:00, 535.89it/s]


tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1]

  0%|          | 0/150 [00:00<?, ?it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

100%|██████████| 150/150 [00:00<00:00, 1250.42it/s]


torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
Epoch [2/25], phase: val, samples: 150, Loss: 0.1391, Top-1 Accuracy: 100.00%


  0%|          | 0/450 [00:00<?, ?it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 11%|█         | 48/450 [00:00<00:00, 436.51it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 22%|██▏       | 101/450 [00:00<00:00, 463.26it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 37%|███▋      | 165/450 [00:00<00:00, 517.48it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 48%|████▊     | 217/450 [00:00<00:00, 482.56it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

 64%|██████▍   | 287/450 [00:00<00:00, 536.85it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 78%|███████▊  | 352/450 [00:00<00:00, 555.02it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 91%|█████████ | 408/450 [00:00<00:00, 510.19it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size

100%|██████████| 450/450 [00:00<00:00, 511.54it/s]


torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
Epoch [3/25], phase: train, samples: 450, Loss: 0.0837, Top-1 Accuracy: 100.00%


 74%|███████▍  | 111/150 [00:00<00:00, 1009.43it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

100%|██████████| 150/150 [00:00<00:00, 1000.34it/s]


torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

  0%|          | 0/450 [00:00<?, ?it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 11%|█         | 48/450 [00:00<00:00, 436.51it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

 22%|██▏       | 97/450 [00:00<00:00, 441.86it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 42%|████▏     | 188/450 [00:00<00:00, 617.97it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 56%|█████▌    | 253/450 [00:00<00:00, 607.37it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 70%|██████▉   | 314/450 [00:00<00:00, 569.71it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size

 83%|████████▎ | 372/450 [00:00<00:00, 539.33it/s]

torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size

 95%|█████████▍| 427/450 [00:00<00:00, 512.26it/s]

torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

100%|██████████| 450/450 [00:00<00:00, 529.59it/s]


torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
Epoch [4/25], phase: train, samples: 450, Loss: 0.0399, Top-1 Accuracy: 99.78%


 30%|███       | 45/150 [00:00<00:00, 1500.48it/s]

torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([0], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([1], device='cuda:0')
torch.Size([1, 1, 10240])
tensor([2], device='cuda:0')
torch.Size

KeyboardInterrupt: 